### ISSUE TITLE
IBF and HIBF 

### ISSUE THREAD

**Issue by lutfia95** [seqan/hibf#102]
Hi Seqan-Team,

I have tested the ability of IBF to store many small protein sequences. I use the alphabet `seqan3::aa27`, the inserted sequences are not very long (maximum `13556` amino acids), but the number of bins is relatively large (`683337` and the RVDB with `34731189` sequences). Since I am classifying peptide sequences, I need to insert the sequences into `683337` (or `34731189` for RVDB) bins. The computed bin size is about (**55.31KiB**) corresponding to the longest sequence, since each bin has the same size. This process results in very high memory footprint since I am dealing with a lot of bins. Do you recommend using HIBF in this case? Actually, I am not interested in where I have the k-mers  (e.g. in FM index), the only thing I would like to classify is each peptide into a specific bin. I thought about using minimizers, but I don't think it will solve the problem.

Best,
Ahmad

**Comment by eseiler** [comment]
I moved this issue to the hibf repo.
I reopened it, so we can discuss your use case until we find a solution that works.

We also added a verbose snippet to the README, which might help understanding the genereal idea.
And we are in the process of adding proper documentation :)

**Comment by lutfia95** [comment]
Hey @smehringer and @eseiler, 

Here is an short example about my use case, inside the lambda function I am generating the k-mers with the corresponding modified version, the iterator is then holding the hash value of each k-mer (either original or modified). The snippet worked well for small fasta file (couple of protein sequences), and I want to test it then on different scenario.  It would be great if you could give me more recommendations on how to improve the build/insert part.

    using traits_type = seqan3::sequence_file_input_default_traits_aa;
    seqan3::sequence_file_input<traits_type> fin{inputFastaFile};

    std::vector<seqan3::aa27_vector> user_bins; 

    for (auto & record : fin)
    {
        user_bins.push_back(record.sequence());
    } 

    auto my_input = [&](size_t const user_bin_id, seqan::hibf::insert_iterator it)
    {
        auto const & seq = user_bins[user_bin_id];
        std::string sequence = "";

        for (auto const & c : seq) sequence += seqan3::to_char(c); 

        const unsigned numberOfKMers = (sequence.length() - kmerSize + 1);

                for(unsigned i = 0; i<numberOfKMers; i++){

                    const std::string kmer = sequence.substr(i, kmerSize);
                    TotalAcceptedPM possibleMutations = this->mutationConf(kmer, threshold);

                    for (const auto& mutatedKmer : possibleMutations.kmers)
                    {
                    // convert std::string to seqan3::a27_vector
                        seqan3::aa27_vector kmerHolder{};
                        for (const char& c : neighbor.first){

                            seqan3::aa27 aminoAcid = {};
                            aminoAcid.assign_char(c);
                            kmerHolder.push_back(aminoAcid);
                        }
                        auto hashValue = this->hashKmer(kmerHolder, kmerSize);
                        it = hashValue;
                        
                    }
                }


    };

    seqan::hibf::config config{.input_fn = my_input,     // required
                               .number_of_user_bins = user_bins.size(), // required
                               .number_of_hash_functions = 2,
                               .maximum_false_positive_rate = 0.01, // recommended to adapt
                               .threads = threads,                        // recommended to adapt
                               .sketch_bits = 12,
                               .tmax = 0, // triggers default copmutation
                               .alpha = 1.2,
                               .max_rearrangement_ratio = 0.5,
                               .disable_estimate_union = false,
                               .disable_rearrangement = false};

    seqan::hibf::hierarchical_interleaved_bloom_filter hibf{config};


Best,
Ahmad

**Comment by eseiler** [comment]
From the HIBF side, this looks good.

From the application side, you might want to try to reduce the number of copies (aa27 -> string -> aa27).
But this depends on how your functions look like.  
For example,

if `mutationConf` takes `std::string_view`, you could use `const std::string_view kmer = std::string_view{sequence}.substr(i, kmerSize);` which doesn't copy.

---

```cpp
for (const auto & mutatedKmer : possibleMutations.kmers)
{
    // convert std::string to seqan3::a27_vector
    seqan3::aa27_vector kmerHolder{};
    for (const char & c : mutatedKmer.first)
    {

        seqan3::aa27 aminoAcid = {};
        aminoAcid.assign_char(c);
        kmerHolder.push_back(aminoAcid);
    }
    auto hashValue = this->hashKmer(kmerHolder, kmerSize);
    it = hashValue;
}
```

could maybe use views (https://docs.seqan.de/seqan3/3.3.0/cookbook.html#cookbook_convert_alphabet_range)

```cpp
for (const auto & mutatedKmer : possibleMutations.kmers)
{
    auto sequence_view = mutatedKmer.first | std::views::transform(
       [](const char in)
       {
           return static_cast<seqan3::aa27>(in);
       });
    auto hashValue = this->hashKmer(sequence_view , kmerSize);
    it = hashValue;
}
```

which would also avoid copies, but requires `hashKmer` to also accept a view.

---

Depending on what else you do, it might also be possible to do everything with either `aa27` or `char` such that you don't have to convert. `seqan3::sequence_file_input` can be told to, e.g., parse the input as `char` but still check that the characters are valid `aa27`.

**Comment by lutfia95** [comment]
Hey @eseiler, 

thank you very much, I already changed to `string_view`. The multithreading part of HIBF is only for the insertion/construction part? or also for the lambda function? I will run the tests today on the complete protein sequences sets. 


Best,
Ahmad

**Comment by eseiler** [comment]
The `config::input_fn` may be called in parallel (by `config::threads` many threads) and the `config::input_fn` will be called twice for each user bin (once for sketch/layout and once for insertion into the HIBF).

**Comment by lutfia95** [comment]
I think the memory usage in my case is very high, inserting the k-mers (only original without any extended k-mers) is also bit high. As I am working with short k-mers such as `k=3,..7` according to the peptide-query sequences. I already tested some scenarios: `k:3` generates `164761541` k-mers from `683337` sequences (refSeqViral), for `k:4` are `164078204` k-mers ...etc. The memory usage for `k:3`was about 78 GB with two hash functions. I was thinking about using minimisers to reduce the raw k-mer set; does `seqan3::views::minimiser_hash(seqan3::shape{seqan3::ungapped{kmerSize}}, seqan3::window_size{8u});` accepts `seqan3::aa27_vector` type? 

Best,
Ahmad

**Comment by lutfia95** [comment]
Hey, 

I could solve the problem by splitting the input reference sequences in parts, instead of generating one HIBF of 1 reference set with 683337 samples, I can use 6 HIBF's. I will close the issue. 
Best.

**Comment by smehringer** [comment]
Hi @lutfia95,

thanks for letting us know. So the main issue was that the HIBF took too much memory, so you split up the reference? We might be working on a partitioned HIBF so I'm asking out of interest.

> It can't be that IBF uses less memory compared to HIBF, as my user bins differ in size.

I would agree, but I cannot say for sure.

From my experiments, `tmax` has the highest impact on the size of the HIBF.
What was you tmax?


Svenja

**Comment by lutfia95** [comment]
Hi @smehringer, 

memory usage was really hight in the case of rearrangement and union estimation (`disable_estimate_union `, `disable_rearrangement `) This problem is solved with disabling both. Second problem is the layout computation time. In the case of using the set of `683337` user bins, this caused very large run time for the layout computation. I didn't have really much time to check the complete implementation from it. So I could solve this problem by splitting the reference set into parts, first I tested different scenarios:   

1-  100000 user bins: `30 threads`, `71,861 minutes` with `tmax = 320`.    
2-  200000 user bins: `30 threads`, `6  hours` with `tmax = 448`.    
3-  300000 user bins: `30 threads`, `11  hours` with `tmax = 576`.    
4- 350000 user bins: `30 threads`, `20  hours` with `tmax = 640`.     

Increasing the number of user-bins will sure increase `tmax`, which will also increase the layout computation time (sketches are fast). I will run the main tests in couple of days and will send you all tested scenarios. 

Ahmad
